### PR TITLE
[WIP] Added some tests to CI (Linux)

### PR DESCRIPTION
**Pull request by mschweiger**
Fixed test target in Makefiles.
Updated comparison data.
Removed debug code in supertoast causing supertoast to abort.

### CODE REVIEW

**Comment by samuelpowell** [comment]
@mschweiger This failed CI last time it ran, do you know what the problem is? There appears to be quite a bit of work here so would be good if we can fix and merge rather than close.

**Comment by samuelpowell** [comment]
CI re-enabled so any pushes to this branch will now trigger, or you can manually rebuild.

**Comment by mschweiger** [comment]
Looks like there is a 50min time limit on travis jobs, so the tests are timing out. I could streamline this by removing the heavy-duty tests, but in the long run the time limit may become a problem.

**Comment by samuelpowell** [comment]
@mschweiger yes, it looks like we need to include only a subset of the tests for CI. I believe that the environment variable `TRAVIS=true` is set when running on Travis, could we switch based upon that?

**Comment by mschweiger** [comment]
@samuelpowell Happy to merge?

**Pull request merged**
