### PR TITLE
More Python fixups

### PR DESCRIPTION
**Pull request by cboulay**
I don't know why there are still some commits in this PR that I thought got merged into your branch already. I might have to make a new branch of py3k and then cherry-pick these 4 commits.

Anyway, a summary of the changes:

Non-Python:
* Exposed more raster mapping matrices
* Tried to fixup the Debug MSVC builds - but that failed.

Everything else was for Python:
* Get various mapping matrices
* Add JacobianOptical to mirror a function in Matlab used by DOTHUB
* Add support for intermediate grid size in basis (Raster)

### CODE REVIEW

**Comment by samuelpowell** [comment]
Fixes fine.

Raster mapping:

Are you just exposing the matrices to the Python interface in order to use the intermediate basis? Can you not just call the library functions, or does the rest of the interface already use the mapping matrices directly? 

Not all methods to transform between bases will use an explicit matrix form so this seems fragile and is why the general procedure is to call a library function (the generated matrices, when they exist, are cached inside the raster object so there shouldn't be a runtime hit). (Note also that there there are different forms of raster mapping, some do basic subsampling, and some explicitly refine the mesh and compute the minimum l2-norm mapping, but the latter are only supported for certain types of mesh).

Jacobians:

What was already exposed? Only a complex frequency domain form? 

I can see that adding the CW (real) form is useful, I am suprised this was not already there. But what is the purpose of the `JacobianOptical`? Is that just for the case that the data are log ratios, e.g. optical densities? The reason I ask is that one might consider this to be a data space transformation, e.g,. d(log y) / dx -> 1/y dy/dx, and thus best managed outside of the library. Is there a precedent for this in the MATLAB interface?

**Comment by cboulay** [comment]
Thanks for the detailed feedback. I'll answer in a couple different posts.

For `JacobianOptical`, I was trying to do an apples-to-apples comparison with the Matlab interface used by [DOTHUB_makeToastJacobian](https://github.com/DOT-HUB/DOT-HUB_toolbox/blob/master/DOTHUB_makeToastJacobian.m#L268). For the same input, can I get the same output?

## Matlab Interface

In Matlab, there are 2 Jacobian functions exposed, but it makes use of overloading so there are effectively 3:
* toastJacobian.m: `toastJacobian (hMesh, hBasis, dphi, aphi, proj)`
* toastJacobian.m optical: `toastJacobian (hMesh, hBasis, qvec, mvec, mua, mus, ref, freq, solver, tol)`
* `toastJacobianCW (mesh, basis, qvec, mvec, mua, mus, ref, solver, tol)`

## Python Interface

The Python interface only [exposed one Jacobian function, equivalent to Matlab's `toastJacobian` (non-optical)](https://github.com/toastpp/toastpp/blob/master/src/python/toastmodule.cc#L1210-L1213). This was a bit surprising because the toastomodule.cc file had 2 `CalcJacobian` implementations, but one of them was unreachable. The unreachable one was equivalent to Matlab's toastJacobian - optical.

There was no equivalent to `toastJacobianCW`. (CW: "continuous wave"; I may have mismatched that in the comments when I was moving code segments around.)

The first change I made was to expose the previously unreachable `CalcJacobian` via `toast_jacobian_optical`. I probably could have made it even closer to the Matlab implementation by using a single (overloaded) function name at the toastmodule.cc level, and then the Python layer could have called the one it wanted with 2 different sets of arguments, but then I'd have to try-catch parsing the arguments and that just seems messy.

The second thing I did was implement something equivalent to `toastJacobianCW`.

Edit:

Sorry, foggy memory after the weekend. I ended up using `JacobianOptical`, even though the Matlab function I was trying to reproduce was `toastJacobianCW`. I found that the upper-left corner of the Jacobian returned by `JacobianOptical` was equivalent to Matlab's `toastJacobianCW`. Unfortunately, `CalcJacobianCW` return wasn't identical to Matlab's, but I couldn't find the difference in the code.

**Comment by cboulay** [comment]
Re Raster mapping,

> Not all methods to transform between bases will use an explicit matrix form so this seems fragile and is why the general procedure is to call a library function.

Yes, I was worried about that at first. However, the only raster type you can get in the Python interface is [`Raster_Pixel`](https://github.com/toastpp/toastpp/blob/master/src/python/toastmodule.cc#L494), so I thought it would be safe to expose the matrices directly.

I want to be able to do real-time sensor->cortex mapping on systems where I can't easily install `pytoast` (e.g., minimal AWS instances). All I need are pre-computed invJacobians and mapping matrices.

**Comment by samuelpowell** [comment]
This can't make things worse, thank you for contribution @cboulay.

~Closes #67.~ Ooops, is on top of #67.

**Pull request merged**
