### PR TITLE
Remove plist (nodal parameter lists) from Mesh class, closes #7

### LINKED ISSUE #7: Refactor to remove parameters from mesh classes
See #8

### PR DESCRIPTION
**Pull request by mschweiger**
This is in response to issue [https://github.com/toastpp/toastpp/issues/7](https://github.com/toastpp/toastpp/issues/7).

The idea is to make the Mesh class define only the geometry of the discretised problem, but exclude application-specific model parameters.

### CODE REVIEW

**Comment by samuelpowell** [comment]
This seems far less disruptive than I had imagined. If I test through the MATLAB interface on OS X will that be enough to uncover any problems?

**Comment by mschweiger** [comment]
Probably yes. My main concern is legacy scripts which may have (unknowingly) used the mesh parameters, e.g. to retrieve a refractive index or diffusion coefficient in order to compute the boundary operators or source positions. I should probably amend the error messages to tell people how to fix the code in those circumstances.

**Comment by samuelpowell** [comment]
Build failing on OS X:

libfdot/util.cc:734:19: No member named 'plist' in 'TOAST_Mesh'
libfdot/util.cc:767:19: No member named 'plist' in 'TOAST_Mesh'

**Comment by samuelpowell** [comment]
@mschweiger I have merged the CI PR and pulled the changes into this branch to enable CI builds - this will confirm when the branch is fixed.

**Comment by samuelpowell** [comment]
@mschweiger disregard CI, this build still fails in util.cc (see #14)

**Comment by samuelpowell** [comment]
@mschweiger I have merged the CI changes into this branch so you can see if it works on with fdot and threads enabled. Note that the OS X util.cc failure still exists.

**Comment by samuelpowell** [comment]
@mschweiger this now passes CI on all architectures, good to merge?

**Pull request merged**
