### PR TITLE
WIP - python compilation restored for Linux and Windows

### PR DESCRIPTION
**Pull request by mschweiger**
This should allow to install the Toast python bindings in Linux and Windows, and run all python tutorials.

More work needed to make Windows installation work out of the box without manually having to copy dependent dlls.

### CODE REVIEW

**Comment by samuelpowell** [comment]
This *should* work on OS X with a little work. The first problem is below:

```
toastmodule.cc:6:10: fatal error: 'toastarch.h' file not found
#include "toastarch.h"
```

Is this normally generated by the Makefile build process?

**Comment by mschweiger** [comment]
No toastarch.h was manually created. I don't know why it hadn't been included so far. It's really only required by Windows to work around Visual Studio language incompatibilities, so its absence may not have been felt before. Anyway, I added it to the python branch now.

**Comment by samuelpowell** [comment]
Okay this builds now but won't link. At some stage during `configure` a symlink is created from `lib` to wherever the native compiler dumps build artefacts. On OS X, the build artefacts are automatically copied into `$TOASTDIR/darwin64/lib` and thus, `lib` should be a symlink to this directory. Can you update this behaviour on OS X or tell me where to make the change?

**Comment by mschweiger** [comment]
The symlink is created by configure, specifically on line 889 of configure.ac. This creates the symlink to $OBJDIR/lib, where $OBJDIR is created on line 764 as

gcc'$CC -v 2>&1 | sed -n 's/gcc version //p' | sed -n 's/ .* .*//p'`

If this construct doesn't work in OS X, then OBJDIR could be set manually for that case, but that requires identifying OS X in configure.ac. Is there a test for OS X that could be used inside configure.ac?

**Comment by samuelpowell** [comment]
I must admit I am not that good with autotools. Running `uname` will return Darwin on OS X, is this enough to build a condition?

**Comment by mschweiger** [comment]
I've modified configure now, but couldn't test it. Can you see if the symlink now points to the correct directory?

**Comment by samuelpowell** [comment]
It seems to, just fixing some other minor problems! ~~Do we need to update the build scripts for CI to build python? I can do that for Linux and OS X, but is there a command line way to do this windows?~~

I have updated the CI for linux and OS X, can you do the same for Windows?

**Comment by samuelpowell** [comment]
@mschweiger almost there.

`make python` fails with:

```
python setup.py build --build-base=/Users/spowell/Documents/toastpp/Darwin64/python
running build
running build_py
running build_ext
python setup.py install
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /Users/spowell/Documents/toastpy/venv/lib/python2.7/site-packages/PyToast-120529-py2.7.egg-info
Writing /Users/spowell/Documents/toastpy/venv/lib/python2.7/site-packages/PyToast-120529-py2.7.egg-info
cd doc; \
	make html
doc: No such file or directory.
make[3]: *** No rule to make target `html'.  Stop.
make[2]: *** [doc] Error 2
make[1]: *** [python] Error 2
make: *** [python] Error 2
```

`examples/recon1.py` and `script/python/tutorials/pmdf.py` fail with

```
Traceback (most recent call last):
  File "pmdf.py", line 30, in <module>
    hmesh = mesh.Read(meshfile)
AttributeError: 'module' object has no attribute 'Read'
```

`script/python/tutorials/recon3.py` runs but goes mad.

All other examples work fine.

**Comment by mschweiger** [comment]
The latest commits should
- fix (well actually skip for now) the doc build problem
- fix examples/recon1.py and script/python/tutorials/pmdf.py

I've also modified setup.py so that it installs the toast module in the local build directory rather than the python default installation directory. This avoids potential permission problems, but requires the user to run ptoast_install.py to set up the search directories.

What was the problem with script/python/tutorials/recon3.py?

**Comment by samuelpowell** [comment]
Okay the build works now, but a couple of quirks

1. At some point a symlink `/toastpp/darwin64/darwin64` is created which points to itself
2. `toastenv.sh` contains the line `export PYTHONPATH=$TOAST_SCRIPT_PATH/python/lib/python2.6/site-packages`, what is this path used for? I assume this should point to site-packages in the build directory, not the script directory? Also, should the python version be hardcoded? It will be 2.7 on OS X up to the latest release.

Finally, I can't actually run the examples now because `toasted.so` can't find Toast's dynamic libraries. This is a more general problem so I think we fix the above I will open an issue and look into this as a separate matter.

**Comment by samuelpowell** [comment]
`recon3.py` executes fine but it never converged

**Comment by mschweiger** [comment]
Latest commits should fix your point 1 above.
I have now added "make_python.bat" in the toast root folder which is a trivial script for building the toast python module in Windows. But I don't know how to add this to CI. Does it need to be referenced in appveyor.yml? Or is that only for building Visual Studio projects?

**Comment by samuelpowell** [comment]
I don't know, let me have a go at making it work, and run the CI on Linux and Mac. I'll let you know if everything shows green!

**Comment by samuelpowell** [comment]
@mschweiger Appveyor is running the .bat file but returns success despite the fact the Python build is failing. At present, the build failure is just because `numpy` is not installed, I will fix this, but before I do, are there any other Python dependencies for the build?

**Comment by mschweiger** [comment]
@samuelpowell Only numpy and scipy should be required. There may also be the odd glumpy dependency, but if this comes up I'll try to remove it since glumpy seems to be obsolete.

**Comment by samuelpowell** [comment]
@mschweiger more progress made in the build progress, but still failing on Appveyor. Any idea what's going on?

**Comment by mschweiger** [comment]
We are still getting error "no numpy.distutils" on linux. Not sure what to make of it. Could this be a numpy version issue?
As to the python build error on Windows - it looks very cryptic, and I can't reproduce it locally.

**Comment by samuelpowell** [comment]
Sorry, I only added numpy to Appveyor, not Travis. Let me fix the latter and take a more aggressive approach to Python on Appveyor. I'd be happy if we could at least get the CI building python on OS X and Linux.

**Comment by samuelpowell** [comment]
@mschweiger I'm trying to incorporate the build script into the Appveyor configuration, do you think the lines you added in 8ef75ec are important?

**Comment by samuelpowell** [comment]
Note that both your modified .bat and my modified Appveyor builds are queued so we'll see if either makes a difference.

**Comment by mschweiger** [comment]
> I'm trying to incorporate the build script into the Appveyor configuration, do you think the lines you added in 8ef75ec are important?

Just a desperate attempt using something found on stackexchange. Hack with slim chance of success, I suspect.

**Comment by samuelpowell** [comment]
Okay, let's see how the CI goes!

**Comment by samuelpowell** [comment]
Good catch

**Comment by samuelpowell** [comment]
@mschweiger okay, Linux is passing (I cancelled some builds that didnt touch travis config). I'm going to put your other fix in the YAML script and see if that helps.

**Comment by samuelpowell** [comment]
If we ever get this to work I think we should squash the commit history to avoid embarrassment.

**Comment by samuelpowell** [comment]
Unless you have any further ideas we could disable the Windows Python CI for now and merge, we do have testing on Linux, at least.

**Comment by mschweiger** [comment]
Yes, I'm out of ideas now. Let's forget about python on Windows CI for now.

**Pull request merged**
