### PR TITLE
[WIP] Fix build against MATLAB >2016a, fixes #13

### LINKED ISSUE #13: Compiling with OS X 10.11.4 / LLVM 7.1 against Matlab R2016a
Hi! 

I just downloaded the current version and tried to compile it on my mac (OS X 10.11.4 / LLVM 7.1, Matlab R2016a) as described in install_mac.html.
Xcode encountered the following issues (I just copied them here, is there a way to generate a niec report from it in Xcode?!):

/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.h:13:13: Typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.h:14:13: Typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:455:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:456:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:496:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:497:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')

So some type casting issue...
Thanks!

### PR DESCRIPTION
**Pull request by samuelpowell**
Define MX_COMPAT_32 before including mex.h which typedefs mwSize to int.

In both cases update all calls to mx routines to use mwSize, apart from when arithmetic is being on the results. This gives compiler warnings in all places where the use of mwSize variables to define matrix dimensions could overflow, but allows builds against 2016a.

### CODE REVIEW

**Comment by samuelpowell** [comment]
On OS X

```
(64-bit mex files using sparse matrices must be rebuilt with the "-largeArrayDims" option.  See the
R2006b release notes for more details.)
```

so MX_COMPAT_32 cannot be defined when building 64 bit. How does this affect Linux/Windows?

**Comment by samuelpowell** [comment]
@mschweiger this builds and runs fine in 64-bits. Do you provide 32-bit MEX files on any platforms? If so, this will need to be tested there.

**Comment by mschweiger** [comment]
@samuelpowell  no, I'm no longer supporting 32-bit builds on any platforms.

**Comment by samuelpowell** [comment]
@mschweiger okay, this is fully tested on OS X. Do you want to build the MATLAB interface on Linux to check it works?

I have rebased against master so this can be merged if it passes your local tests and CI.

**Comment by mschweiger** [comment]
@samuelpowell The order of header #includes seems to have changed in quite a few of the sources for the mex build. For example, in matlabtoast.cc it used to be

#include "matlabtoast.h"
#include "mexutil.h"

Now it's the other way round. Is there a reason for this? It causes the Linux build to fail quite spectacularly.

**Comment by samuelpowell** [comment]
I changed the order so that MX_COMPAT_32 was defined before including mex.h, but if we don't need to support 32-bit architectures then I will revert that change. I'll ping you when done.

**Comment by samuelpowell** [comment]
@mschweiger I have reverted the changes to header ordering, this still works on OS X, let me know if it helps.

**Comment by mschweiger** [comment]
@samuelpowell All is well again. The latest commit compiles and runs the mex file both on Linux and Windows.

**Pull request merged**
